version: '3'

services:

  flask:
    build:
      context: ./services/server
      dockerfile: Dockerfile.x86
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=flashcards.config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  flashcards:
    build:
      context: ./services/client
      dockerfile: Dockerfile.x86
    ports:
      - 80:80
      - 443:443
    links:
      - flask
# Uncomment for hot reload during development
#    volumes:
#      - ./services/client/src:/usr/share/nginx/html
