#!/usr/bin/env bash
CONTROLLER=10.0.2.10
KUBECONFIG=${HOME}/pikubeconfig
KUBE_CONFIG_PATH=$KUBECONFIG
export KUBECONFIG
export KUBE_CONFIG_PATH

_boot_locally() {
  docker-compose down
  docker-compose up -d --build
  docker-compose exec flask python manage.py recreate_db
  docker-compose exec flask python manage.py seed_db
}

get_kubeconfig() {
  echo "Getting kubeconfig file from ${CONTROLLER} and writting to ${KUBECONFIG}"
  echo "Set the ENV var KUBECONFIG=${KUBECONFIG} to use this"
  ssh pi@${CONTROLLER} sudo cat /etc/rancher/k3s/k3s.yaml | sed -e s/127.0.0.1/${CONTROLLER}/g >${KUBECONFIG}
}

help() {
  echo "usage $0 get_kubeconfig | kubectl <options> | terraform <options> "
  exit 1
}

_kubectl() {
  kubectl $@
}

_terraform() {
  cd terraform
  terraform $@
  cd -
}

CMD=${1:-}
shift || true
case ${CMD} in
boot) _boot_locally ;;
get_kubeconfig) get_kubeconfig ;;
kubectl) _kubectl $@ ;;
terraform) _terraform $@ ;;
*) help ;;
esac
