#!/usr/bin/env bash
CONTROLLER=pi0
KUBECONFIG=${HOME}/pikubeconfig
KUBE_CONFIG_PATH=$KUBECONFIG
export KUBECONFIG
export KUBE_CONFIG_PATH

run_e2e_tests() {
  ./scripts/test.sh e2e
}

start_locally() {
  ./scripts/test.sh start
}

stop_locally() {
  ./scripts/test.sh stop
}

get_kubeconfig() {
  echo "Getting kubeconfig file from ${CONTROLLER} and writting to ${KUBECONFIG}"
  echo "Set the ENV var KUBECONFIG=${KUBECONFIG} to use this"
  ssh pi@${CONTROLLER} sudo cat /etc/rancher/k3s/k3s.yaml | sed -e s/127.0.0.1/${CONTROLLER}/g >${KUBECONFIG}
}

help() {
  echo "usage $0 get_kubeconfig | kubectl <options> | terraform <options> | e2e | start | stop"
  exit 1
}

_kubectl() {
  kubectl $@
}

_terraform() {
  cd terraform
  terraform $@
  cd -
}

CMD=${1:-}
shift || true
case ${CMD} in
e2e) run_e2e_tests ;;
start) start_locally ;;
stop) stop_locally ;;
get_kubeconfig) get_kubeconfig ;;
kubectl) _kubectl $@ ;;
terraform) _terraform $@ ;;
*) help ;;
esac
