version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - browser-tools/install-chrome

      - run:
          name: Install python packages
          command: sudo pip install chromedriver-py pytest selenium

      - run:
          name: Run end-to-end test
          command: ./scripts/test.sh

  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
#      - add_ssh_keys
      - setup_remote_docker

      - run:
          name: Build and push Docker images
          command: ./scripts/build.sh

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Deploy services
          command: ./scripts/deploy.sh

orbs:
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
