version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - add_ssh_keys
      - browser-tools/install-chrome-driver

      - setup_remote_docker:

      - run:
          name: Build and push Docker images
          command: ./scripts/build.sh

#      - run:
#          name: Install awscli
#          command: sudo pip install awscli
#
#      - run:
#          name: Deploy services
#          command: ./scripts/deploy.sh

orbs:
  browser-tools: circleci/browser-tools@1.1.3
