version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout

      - run:
          name: Print commit hash of last successful build
          command: curl -Ss -u "${CIRCLE_API_USER_TOKEN}:" "https://circleci.com/api/v1.1/project/github/neinkeinkaffee/flashcards?filter=completed&limit=1" | jq -r '.[0]["vcs_revision"]'

      - run:
          name: Run frontend unit tests
          command: ./scripts/test.sh js

      - run:
          name: Run backend unit tests
          command: ./scripts/test.sh flask

      - run:
          name: Run end-to-end test
          command: ./scripts/test.sh e2e

  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
#      - add_ssh_keys
      - setup_remote_docker

      - run:
          name: Build and push Docker images
          command: ./scripts/build.sh

#      - run:
#          name: Install awscli
#          command: sudo pip install awscli
#
#      - run:
#          name: Deploy services
#          command: ./scripts/deploy.sh

orbs:
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
