version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 manage.py test

      - setup_remote_docker:

      - run:
          name: Build and push Docker images
          command: ./scripts/build.sh

  deploy:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout

      - add_ssh_keys

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Deploy services
          command: ./scripts/deploy.sh





