version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./services/server/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "./services/server/requirements.txt" }}

#      - run:
#          name: run tests
#          command: |
#            . venv/bin/activate
#            python manage.py test
#
#      - store_artifacts:
#          path: test-reports
#          destination: test-reports

      - setup_remote_docker:
      - run:
          command: |
            echo $DOCKER_HUB_PASSWORD | base64 --decode | docker login --username $DOCKER_HUB_NAMESPACE --password-stdin
            docker run --rm --privileged multiarch/qemu-user-static:register
            docker build -t $DOCKER_HUB_NAMESPACE/flashcards-nginx ./services/server
            docker push $DOCKER_HUB_NAMESPACE/flashcards-nginx




