apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: flashcards-lan-things-on-top-of-other-things-de
  namespace: default
spec:
  secretName: flashcards-lan-things-on-top-of-other-things-de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: flashcards.lan.things-on-top-of-other-things.de
  dnsNames:
  - flashcards.lan.things-on-top-of-other-things.de
