apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    service: nginx
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30080
  - port: 443
    name: https
    targetPort: 443
    nodePort: 30443

